### PR TITLE
let the user decide when to initialize the init add_action method 

### PR DESCRIPTION
**Pull request by ghost**
let the user decide when to initialize the init method and also added root namespace for add_action

### CODE REVIEW

**Comment by philipnewcomer** [comment]
@eettmm thanks for contributing.

Can you describe the problem you trying to solve with this PR so I can understand the purpose of these changes?

**Comment by ghost** [comment]
The issue I'm having is that the composer's autoload.php file is loading before WordPress is loaded. So it is  throwing 

> Fatal error: Uncaught Error: Call to undefined function add_action() in /home/veda/deployments/rio/vendor/philipnewcomer/acf-unique-id-field/src/init.php:5

but with this pull-request, you can control when you want to run hook for `acf/include_field_types`

**Comment by philipnewcomer** [comment]
@eettmm I've been playing around with this and it looks like it works to move the `init()` static method to the `ACF_Field_Unique_ID` class itself, and do away with a separate loader class. That seems cleaner to me. And we can also use PSR-4 autoloading that way.

**Comment by philipnewcomer** [comment]
@eettmm thanks for the PR!

**Pull request merged**
